const ropaHombre = [
    {
        imagen1 : "/PRODUCTOS/ROPA/Ropa Hombre/Ropa1/1.jpeg",
        imagen2 : "/PRODUCTOS/ROPA/Ropa Hombre/Ropa1/2.jpeg",
        imagen3 : "/PRODUCTOS/ROPA/Ropa Hombre/Ropa1/3.jpeg",
        imagen4 : "/PRODUCTOS/ROPA/Ropa Hombre/Ropa1/4.jpeg",
        nombre: "Nombre Prenda:",
        talla: "Talla:",
        colores: "Colores Disponibles:",
        precio: "Precio: $$$$",
        codigo: "000001"
    },
    {
        imagen1 : "/PRODUCTOS/ROPA/Ropa Hombre/Ropa2/1.jpeg",
        imagen2 : "/PRODUCTOS/ROPA/Ropa Hombre/Ropa2/2.jpeg",
        imagen3 : "/PRODUCTOS/ROPA/Ropa Hombre/Ropa2/3.jpeg",
        imagen4 : "/PRODUCTOS/ROPA/Ropa Hombre/Ropa2/4.jpeg",
        imagen5 : "/PRODUCTOS/ROPA/Ropa Hombre/Ropa2/5.jpeg",
        nombre: "Nombre Prenda:",
        talla: "Talla:",
        colores: "Colores Disponibles:",
        precio: "Precio: $$$$",
        codigo: "000002"
    },
    {
        imagen1 : "/PRODUCTOS/ROPA/Ropa Hombre/Ropa3/1.jpeg",
        imagen2 : "/PRODUCTOS/ROPA/Ropa Hombre/Ropa3/2.jpeg",
        imagen3 : "/PRODUCTOS/ROPA/Ropa Hombre/Ropa3/3.jpeg",
        imagen4 : "/PRODUCTOS/ROPA/Ropa Hombre/Ropa3/4.jpeg",
        imagen5 : "/PRODUCTOS/ROPA/Ropa Hombre/Ropa3/5.jpeg",
        nombre: "Nombre Prenda:",
        talla: "Talla:",
        colores: "Colores Disponibles:",
        precio: "Precio: $$$$",
        codigo: "000003"
    },
    {
        imagen1 : "/PRODUCTOS/ROPA/Ropa Hombre/Ropa4/1.jpeg",
        imagen2 : "/PRODUCTOS/ROPA/Ropa Hombre/Ropa4/2.jpeg",
        imagen3 : "/PRODUCTOS/ROPA/Ropa Hombre/Ropa4/3.jpeg",
        nombre: "Nombre Prenda:",
        talla: "Talla:",
        colores: "Colores Disponibles:",
        precio: "Precio: $$$$",
        codigo: "000004"
    },
    {
        imagen1 : "/PRODUCTOS/ROPA/Ropa Hombre/Ropa5/1.jpeg",
        imagen2 : "/PRODUCTOS/ROPA/Ropa Hombre/Ropa5/2.jpeg",
        imagen3 : "/PRODUCTOS/ROPA/Ropa Hombre/Ropa5/3.jpeg",
        imagen4 : "/PRODUCTOS/ROPA/Ropa Hombre/Ropa5/4.jpeg",
        nombre: "Nombre Prenda:",
        talla: "Talla:",
        colores: "Colores Disponibles:",
        precio: "Precio: $$$$",
        codigo: "000005"
    },
    {
        imagen1 : "/PRODUCTOS/ROPA/Ropa Hombre/Ropa6/1.jpeg",
        imagen2 : "/PRODUCTOS/ROPA/Ropa Hombre/Ropa6/2.jpeg",
        imagen3 : "/PRODUCTOS/ROPA/Ropa Hombre/Ropa6/3.jpeg",
        imagen4 : "/PRODUCTOS/ROPA/Ropa Hombre/Ropa6/4.jpeg",
        imagen5 : "/PRODUCTOS/ROPA/Ropa Hombre/Ropa6/5.jpeg",
        imagen6 : "/PRODUCTOS/ROPA/Ropa Hombre/Ropa6/6.jpeg",
        nombre: "Nombre Prenda:",
        talla: "Talla:",
        colores: "Colores Disponibles:",
        precio: "Precio: $$$$",
        codigo: "000006"
    },
    {
        imagen1 : "/PRODUCTOS/ROPA/Ropa Hombre/Ropa7/1.jpeg",
        imagen2 : "/PRODUCTOS/ROPA/Ropa Hombre/Ropa7/2.jpeg",
        imagen3 : "/PRODUCTOS/ROPA/Ropa Hombre/Ropa7/3.jpeg",
        imagen4 : "/PRODUCTOS/ROPA/Ropa Hombre/Ropa7/4.jpeg",
        imagen5 : "/PRODUCTOS/ROPA/Ropa Hombre/Ropa7/5.jpeg",
        imagen6 : "/PRODUCTOS/ROPA/Ropa Hombre/Ropa7/6.jpeg",
        nombre: "Nombre Prenda:",
        talla: "Talla:",
        colores: "Colores Disponibles:",
        precio: "Precio: $$$$",
        codigo: "000007"
    },
    {
        imagen1 : "/PRODUCTOS/ROPA/Ropa Hombre/Ropa8/1.jpeg",
        imagen2 : "/PRODUCTOS/ROPA/Ropa Hombre/Ropa8/2.jpeg",
        imagen3 : "/PRODUCTOS/ROPA/Ropa Hombre/Ropa8/3.jpeg",
        nombre: "Nombre Prenda:",
        talla: "Talla:",
        colores: "Colores Disponibles:",
        precio: "Precio: $$$$",
        codigo: "000008"
    },
    {
        imagen1 : "/PRODUCTOS/ROPA/Ropa Hombre/Ropa9/1.jpeg",
        imagen2 : "/PRODUCTOS/ROPA/Ropa Hombre/Ropa9/2.jpeg",
        imagen3 : "/PRODUCTOS/ROPA/Ropa Hombre/Ropa9/3.jpeg",
        imagen4 : "/PRODUCTOS/ROPA/Ropa Hombre/Ropa9/4.jpeg",
        nombre: "Nombre Prenda:",
        talla: "Talla:",
        colores: "Colores Disponibles:",
        precio: "Precio: $$$$",
        codigo: "000009"
    },
    {
        imagen1 : "/PRODUCTOS/ROPA/Ropa Hombre/Ropa10/1.jpeg",
        imagen2 : "/PRODUCTOS/ROPA/Ropa Hombre/Ropa10/2.jpeg",
        imagen3 : "/PRODUCTOS/ROPA/Ropa Hombre/Ropa10/3.jpeg",
        imagen4 : "/PRODUCTOS/ROPA/Ropa Hombre/Ropa10/4.jpeg",
        imagen5 : "/PRODUCTOS/ROPA/Ropa Hombre/Ropa10/5.jpeg",
        nombre: "Nombre Prenda:",
        talla: "Talla:",
        colores: "Colores Disponibles:",
        precio: "Precio: $$$$",
        codigo: "000010"
    },
    {
        imagen1 : "/PRODUCTOS/ROPA/Ropa Hombre/Ropa11/1.jpeg",
        imagen2 : "/PRODUCTOS/ROPA/Ropa Hombre/Ropa11/2.jpeg",
        imagen3 : "/PRODUCTOS/ROPA/Ropa Hombre/Ropa11/3.jpeg",
        imagen4 : "/PRODUCTOS/ROPA/Ropa Hombre/Ropa11/4.jpeg",
        imagen5 : "/PRODUCTOS/ROPA/Ropa Hombre/Ropa11/5.jpeg",
        nombre: "Nombre Prenda:",
        talla: "Talla:",
        colores: "Colores Disponibles:",
        precio: "Precio: $$$$",
        codigo: "000011"
    },
    {
        imagen1 : "/PRODUCTOS/ROPA/Ropa Hombre/Ropa12/1.jpeg",
        imagen2 : "/PRODUCTOS/ROPA/Ropa Hombre/Ropa12/2.jpeg",
        imagen3 : "/PRODUCTOS/ROPA/Ropa Hombre/Ropa12/3.jpeg",
        imagen4 : "/PRODUCTOS/ROPA/Ropa Hombre/Ropa12/4.jpeg",
        nombre: "Nombre Prenda:",
        talla: "Talla:",
        colores: "Colores Disponibles:",
        precio: "Precio: $$$$",
        codigo: "000012"
    },
    {
        imagen1 : "/PRODUCTOS/ROPA/Ropa Hombre/Ropa13/1.jpeg",
        imagen2 : "/PRODUCTOS/ROPA/Ropa Hombre/Ropa13/2.jpeg",
        imagen3 : "/PRODUCTOS/ROPA/Ropa Hombre/Ropa13/3.jpeg",
        imagen4 : "/PRODUCTOS/ROPA/Ropa Hombre/Ropa13/4.jpeg",
        imagen5 : "/PRODUCTOS/ROPA/Ropa Hombre/Ropa13/5.jpeg",
        imagen6 : "/PRODUCTOS/ROPA/Ropa Hombre/Ropa13/6.jpeg",
        imagen7 : "/PRODUCTOS/ROPA/Ropa Hombre/Ropa13/7.jpeg",
        nombre: "Nombre Prenda:",
        talla: "Talla:",
        colores: "Colores Disponibles:",
        precio: "Precio: $$$$",
        codigo: "000013"
    },
    {
        imagen1 : "/PRODUCTOS/ROPA/Ropa Hombre/Ropa14/1.jpeg",
        imagen2 : "/PRODUCTOS/ROPA/Ropa Hombre/Ropa14/2.jpeg",
        imagen3 : "/PRODUCTOS/ROPA/Ropa Hombre/Ropa14/3.jpeg",
        imagen4 : "/PRODUCTOS/ROPA/Ropa Hombre/Ropa14/4.jpeg",
        nombre: "Nombre Prenda:",
        talla: "Talla:",
        colores: "Colores Disponibles:",
        precio: "Precio: $$$$",
        codigo: "000014"
    },
    {
        imagen1 : "/PRODUCTOS/ROPA/Ropa Hombre/Ropa15/1.jpeg",
        imagen2 : "/PRODUCTOS/ROPA/Ropa Hombre/Ropa15/2.jpeg",
        imagen3 : "/PRODUCTOS/ROPA/Ropa Hombre/Ropa15/3.jpeg",
        imagen4 : "/PRODUCTOS/ROPA/Ropa Hombre/Ropa15/4.jpeg",
        imagen5 : "/PRODUCTOS/ROPA/Ropa Hombre/Ropa15/5.jpeg",
        imagen6 : "/PRODUCTOS/ROPA/Ropa Hombre/Ropa15/6.jpeg",
        imagen7 : "/PRODUCTOS/ROPA/Ropa Hombre/Ropa15/7.jpeg",
        nombre: "Nombre Prenda:",
        talla: "Talla:",
        colores: "Colores Disponibles:",
        precio: "Precio: $$$$",
        codigo: "000015"
    },
]