const ropaNiña = [
    {
        imagen1 : "/PRODUCTOS/ROPA/Ropa Niña/Ropa1/1.jpg",
        imagen2 : "/PRODUCTOS/ROPA/Ropa Niña/Ropa1/2.jpg",
        imagen3 : "/PRODUCTOS/ROPA/Ropa Niña/Ropa1/3.jpg",
        imagen4 : "/PRODUCTOS/ROPA/Ropa Niña/Ropa1/4.jpg",
        nombre: "Nombre Prenda:",
        talla: "Talla:",
        colores: "Colores Disponibles:",
        precio: "Precio: $$$$",
        codigo: "000031"
    },
    {
        imagen1 : "/PRODUCTOS/ROPA/Ropa Niña/Ropa2/1.jpg",
        imagen2 : "/PRODUCTOS/ROPA/Ropa Niña/Ropa2/2.jpg",
        imagen3 : "/PRODUCTOS/ROPA/Ropa Niña/Ropa2/3.jpg",
        imagen4 : "/PRODUCTOS/ROPA/Ropa Niña/Ropa2/4.jpg",
        nombre: "Nombre Prenda:",
        talla: "Talla:",
        colores: "Colores Disponibles:",
        precio: "Precio: $$$$",
        codigo: "000032"
    },
    {
        imagen1 : "/PRODUCTOS/ROPA/Ropa Niña/Ropa3/1.jpg",
        imagen2 : "/PRODUCTOS/ROPA/Ropa Niña/Ropa3/2.jpg",
        imagen3 : "/PRODUCTOS/ROPA/Ropa Niña/Ropa3/3.jpg",
        imagen4 : "/PRODUCTOS/ROPA/Ropa Niña/Ropa3/4.jpg",
        imagen5 : "/PRODUCTOS/ROPA/Ropa Niña/Ropa3/5.jpg",
        imagen6 : "/PRODUCTOS/ROPA/Ropa Niña/Ropa3/6.jpg",
        nombre: "Nombre Prenda:",
        talla: "Talla:",
        colores: "Colores Disponibles:",
        precio: "Precio: $$$$",
        codigo: "000033"
    },
    {
        imagen1 : "/PRODUCTOS/ROPA/Ropa Niña/Ropa4/1.jpg",
        imagen2 : "/PRODUCTOS/ROPA/Ropa Niña/Ropa4/2.jpg",
        imagen3 : "/PRODUCTOS/ROPA/Ropa Niña/Ropa4/3.jpg",
        nombre: "Nombre Prenda:",
        talla: "Talla:",
        colores: "Colores Disponibles:",
        precio: "Precio: $$$$",
        codigo: "000034"
    },
    {
        imagen1 : "/PRODUCTOS/ROPA/Ropa Niña/Ropa5/1.jpg",
        imagen2 : "/PRODUCTOS/ROPA/Ropa Niña/Ropa5/2.jpg",
        imagen3 : "/PRODUCTOS/ROPA/Ropa Niña/Ropa5/3.jpg",
        imagen4 : "/PRODUCTOS/ROPA/Ropa Niña/Ropa5/4.jpg",
        nombre: "Nombre Prenda:",
        talla: "Talla:",
        colores: "Colores Disponibles:",
        precio: "Precio: $$$$",
        codigo: "000035"
    },
    {
        imagen1 : "/PRODUCTOS/ROPA/Ropa Niña/Ropa6/1.jpg",
        imagen2 : "/PRODUCTOS/ROPA/Ropa Niña/Ropa6/2.jpg",
        imagen3 : "/PRODUCTOS/ROPA/Ropa Niña/Ropa6/3.jpg",
        imagen4 : "/PRODUCTOS/ROPA/Ropa Niña/Ropa6/4.jpg",
        imagen5 : "/PRODUCTOS/ROPA/Ropa Niña/Ropa6/5.jpg",
        imagen6 : "/PRODUCTOS/ROPA/Ropa Niña/Ropa6/6.jpg",
        nombre: "Nombre Prenda:",
        talla: "Talla:",
        colores: "Colores Disponibles:",
        precio: "Precio: $$$$",
        codigo: "000036"
    },
    {
        imagen1 : "/PRODUCTOS/ROPA/Ropa Niña/Ropa7/1.jpg",
        imagen2 : "/PRODUCTOS/ROPA/Ropa Niña/Ropa7/2.jpg",
        imagen3 : "/PRODUCTOS/ROPA/Ropa Niña/Ropa7/3.jpg",
        imagen4 : "/PRODUCTOS/ROPA/Ropa Niña/Ropa7/4.jpg",
        nombre: "Nombre Prenda:",
        talla: "Talla:",
        colores: "Colores Disponibles:",
        precio: "Precio: $$$$",
        codigo: "000037"
    },
    {
        imagen1 : "/PRODUCTOS/ROPA/Ropa Niña/Ropa8/1.jpg",
        imagen2 : "/PRODUCTOS/ROPA/Ropa Niña/Ropa8/2.jpg",
        imagen3 : "/PRODUCTOS/ROPA/Ropa Niña/Ropa8/3.jpg",
        imagen4 : "/PRODUCTOS/ROPA/Ropa Niña/Ropa8/4.jpg",
        imagen5 : "/PRODUCTOS/ROPA/Ropa Niña/Ropa8/5.jpg",
        nombre: "Nombre Prenda:",
        talla: "Talla:",
        colores: "Colores Disponibles:",
        precio: "Precio: $$$$",
        codigo: "000038"
    },
    {
        imagen1 : "/PRODUCTOS/ROPA/Ropa Niña/Ropa9/1.jpg",
        imagen2 : "/PRODUCTOS/ROPA/Ropa Niña/Ropa9/2.jpg",
        imagen3 : "/PRODUCTOS/ROPA/Ropa Niña/Ropa9/3.jpg",
        nombre: "Nombre Prenda:",
        talla: "Talla:",
        colores: "Colores Disponibles:",
        precio: "Precio: $$$$",
        codigo: "000039"
    },
    {
        imagen1 : "/PRODUCTOS/ROPA/Ropa Niña/Ropa10/1.jpg",
        imagen2 : "/PRODUCTOS/ROPA/Ropa Niña/Ropa10/2.jpg",
        imagen3 : "/PRODUCTOS/ROPA/Ropa Niña/Ropa10/3.jpg",
        imagen4 : "/PRODUCTOS/ROPA/Ropa Niña/Ropa10/4.jpg",
        imagen5 : "/PRODUCTOS/ROPA/Ropa Niña/Ropa10/5.jpg",
        imagen6 : "/PRODUCTOS/ROPA/Ropa Niña/Ropa10/6.jpg",
        nombre: "Nombre Prenda:",
        talla: "Talla:",
        colores: "Colores Disponibles:",
        precio: "Precio: $$$$",
        codigo: "000040"
    },
    {
        imagen1 : "/PRODUCTOS/ROPA/Ropa Niña/Ropa11/1.jpg",
        imagen2 : "/PRODUCTOS/ROPA/Ropa Niña/Ropa11/2.jpg",
        imagen3 : "/PRODUCTOS/ROPA/Ropa Niña/Ropa11/3.jpg",
        imagen4 : "/PRODUCTOS/ROPA/Ropa Niña/Ropa11/4.jpg",
        imagen5 : "/PRODUCTOS/ROPA/Ropa Niña/Ropa11/5.jpg",
        imagen6 : "/PRODUCTOS/ROPA/Ropa Niña/Ropa11/6.jpg",
        imagen7 : "/PRODUCTOS/ROPA/Ropa Niña/Ropa11/7.jpg",
        nombre: "Nombre Prenda:",
        talla: "Talla:",
        colores: "Colores Disponibles:",
        precio: "Precio: $$$$",
        codigo: "000041"
    },
    {
        imagen1 : "/PRODUCTOS/ROPA/Ropa Niña/Ropa12/1.jpg",
        imagen2 : "/PRODUCTOS/ROPA/Ropa Niña/Ropa12/2.jpg",
        imagen3 : "/PRODUCTOS/ROPA/Ropa Niña/Ropa12/3.jpg",
        nombre: "Nombre Prenda:",
        talla: "Talla:",
        colores: "Colores Disponibles:",
        precio: "Precio: $$$$",
        codigo: "000042"
    },
    {
        imagen1 : "/PRODUCTOS/ROPA/Ropa Niña/Ropa13/1.jpg",
        imagen2 : "/PRODUCTOS/ROPA/Ropa Niña/Ropa13/2.jpg",
        imagen3 : "/PRODUCTOS/ROPA/Ropa Niña/Ropa13/3.jpg",
        imagen4 : "/PRODUCTOS/ROPA/Ropa Niña/Ropa13/4.jpg",
        imagen5 : "/PRODUCTOS/ROPA/Ropa Niña/Ropa13/5.jpg",
        nombre: "Nombre Prenda:",
        talla: "Talla:",
        colores: "Colores Disponibles:",
        precio: "Precio: $$$$",
        codigo: "000043"
    },
    {
        imagen1 : "/PRODUCTOS/ROPA/Ropa Niña/Ropa14/1.jpg",
        imagen2 : "/PRODUCTOS/ROPA/Ropa Niña/Ropa14/2.jpg",
        imagen3 : "/PRODUCTOS/ROPA/Ropa Niña/Ropa14/3.jpg",
        imagen4 : "/PRODUCTOS/ROPA/Ropa Niña/Ropa14/4.jpg",
        imagen5 : "/PRODUCTOS/ROPA/Ropa Niña/Ropa14/5.jpg",
        imagen6 : "/PRODUCTOS/ROPA/Ropa Niña/Ropa14/6.jpg",
        nombre: "Nombre Prenda:",
        talla: "Talla:",
        colores: "Colores Disponibles:",
        precio: "Precio: $$$$",
        codigo: "000044"
    },
    {
        imagen1 : "/PRODUCTOS/ROPA/Ropa Niña/Ropa15/1.jpg",
        imagen2 : "/PRODUCTOS/ROPA/Ropa Niña/Ropa15/2.jpg",
        imagen3 : "/PRODUCTOS/ROPA/Ropa Niña/Ropa15/3.jpg",
        imagen4 : "/PRODUCTOS/ROPA/Ropa Niña/Ropa15/4.jpg",
        imagen5 : "/PRODUCTOS/ROPA/Ropa Niña/Ropa15/5.jpg",
        imagen6 : "/PRODUCTOS/ROPA/Ropa Niña/Ropa15/6.jpg",
        imagen7 : "/PRODUCTOS/ROPA/Ropa Niña/Ropa15/7.jpg",
        imagen8 : "/PRODUCTOS/ROPA/Ropa Niña/Ropa15/8.jpg",
        imagen9 : "/PRODUCTOS/ROPA/Ropa Niña/Ropa15/9.jpg",
        nombre: "Nombre Prenda:",
        talla: "Talla:",
        colores: "Colores Disponibles:",
        precio: "Precio: $$$$",
        codigo: "000045"
    },
]