const ropaNiño = [
    {
        imagen1 : "/PRODUCTOS/ROPA/Ropa Niño/Ropa1/1.jpg",
        imagen2 : "/PRODUCTOS/ROPA/Ropa Niño/Ropa1/2.jpg",
        imagen3 : "/PRODUCTOS/ROPA/Ropa Niño/Ropa1/3.jpg",
        imagen4 : "/PRODUCTOS/ROPA/Ropa Niño/Ropa1/4.jpg",
        imagen5 : "/PRODUCTOS/ROPA/Ropa Niño/Ropa1/5.jpg",
        imagen6 : "/PRODUCTOS/ROPA/Ropa Niño/Ropa1/6.jpg",
        nombre: "Nombre Prenda:",
        talla: "Talla:",
        colores: "Colores Disponibles:",
        precio: "Precio: $$$$",
        codigo: "000046"
    },
    {
        imagen1 : "/PRODUCTOS/ROPA/Ropa Niño/Ropa2/1.jpg",
        imagen2 : "/PRODUCTOS/ROPA/Ropa Niño/Ropa2/2.jpg",
        imagen3 : "/PRODUCTOS/ROPA/Ropa Niño/Ropa2/3.jpg",
        imagen4 : "/PRODUCTOS/ROPA/Ropa Niño/Ropa2/4.jpg",
        nombre: "Nombre Prenda:",
        talla: "Talla:",
        colores: "Colores Disponibles:",
        precio: "Precio: $$$$",
        codigo: "000047"
    },
    {
        imagen1 : "/PRODUCTOS/ROPA/Ropa Niño/Ropa3/1.jpg",
        imagen2 : "/PRODUCTOS/ROPA/Ropa Niño/Ropa3/2.jpg",
        imagen3 : "/PRODUCTOS/ROPA/Ropa Niño/Ropa3/3.jpg",
        imagen4 : "/PRODUCTOS/ROPA/Ropa Niño/Ropa3/4.jpg",
        nombre: "Nombre Prenda:",
        talla: "Talla:",
        colores: "Colores Disponibles:",
        precio: "Precio: $$$$",
        codigo: "000048"
    },
    {
        imagen1 : "/PRODUCTOS/ROPA/Ropa Niño/Ropa4/1.jpg",
        imagen2 : "/PRODUCTOS/ROPA/Ropa Niño/Ropa4/2.jpg",
        imagen3 : "/PRODUCTOS/ROPA/Ropa Niño/Ropa4/3.jpg",
        imagen4 : "/PRODUCTOS/ROPA/Ropa Niño/Ropa4/4.jpg",
        imagen5 : "/PRODUCTOS/ROPA/Ropa Niño/Ropa4/5.jpg",
        imagen6 : "/PRODUCTOS/ROPA/Ropa Niño/Ropa4/6.jpg",
        imagen7 : "/PRODUCTOS/ROPA/Ropa Niño/Ropa4/7.jpg",
        imagen8 : "/PRODUCTOS/ROPA/Ropa Niño/Ropa4/8.jpg",
        imagen9 : "/PRODUCTOS/ROPA/Ropa Niño/Ropa4/9.jpg",
        imagen10 : "/PRODUCTOS/ROPA/Ropa Niño/Ropa4/10.jpg",
        nombre: "Nombre Prenda:",
        talla: "Talla:",
        colores: "Colores Disponibles:",
        precio: "Precio: $$$$",
        codigo: "000049"
    },
    {
        imagen1 : "/PRODUCTOS/ROPA/Ropa Niño/Ropa5/1.jpg",
        imagen2 : "/PRODUCTOS/ROPA/Ropa Niño/Ropa5/2.jpg",
        imagen3 : "/PRODUCTOS/ROPA/Ropa Niño/Ropa5/3.jpg",
        imagen4 : "/PRODUCTOS/ROPA/Ropa Niño/Ropa5/4.jpg",
        imagen5 : "/PRODUCTOS/ROPA/Ropa Niño/Ropa5/5.jpg",
        imagen6 : "/PRODUCTOS/ROPA/Ropa Niño/Ropa5/6.jpg",
        nombre: "Nombre Prenda:",
        talla: "Talla:",
        colores: "Colores Disponibles:",
        precio: "Precio: $$$$",
        codigo: "000050"
    },
    {
        imagen1 : "/PRODUCTOS/ROPA/Ropa Niño/Ropa6/1.jpg",
        imagen2 : "/PRODUCTOS/ROPA/Ropa Niño/Ropa6/2.jpg",
        imagen3 : "/PRODUCTOS/ROPA/Ropa Niño/Ropa6/3.jpg",
        imagen4 : "/PRODUCTOS/ROPA/Ropa Niño/Ropa6/4.jpg",
        imagen5 : "/PRODUCTOS/ROPA/Ropa Niño/Ropa6/5.jpg",
        imagen6 : "/PRODUCTOS/ROPA/Ropa Niño/Ropa6/6.jpg",
        imagen7 : "/PRODUCTOS/ROPA/Ropa Niño/Ropa6/7.jpg",
        imagen8 : "/PRODUCTOS/ROPA/Ropa Niño/Ropa6/8.jpg",
        nombre: "Nombre Prenda:",
        talla: "Talla:",
        colores: "Colores Disponibles:",
        precio: "Precio: $$$$",
        codigo: "000051"
    },
    {
        imagen1 : "/PRODUCTOS/ROPA/Ropa Niño/Ropa7/1.jpg",
        imagen2 : "/PRODUCTOS/ROPA/Ropa Niño/Ropa7/2.jpg",
        imagen3 : "/PRODUCTOS/ROPA/Ropa Niño/Ropa7/3.jpg",
        imagen4 : "/PRODUCTOS/ROPA/Ropa Niño/Ropa7/4.jpg",
        imagen5 : "/PRODUCTOS/ROPA/Ropa Niño/Ropa7/5.jpg",
        nombre: "Nombre Prenda:",
        talla: "Talla:",
        colores: "Colores Disponibles:",
        precio: "Precio: $$$$",
        codigo: "000052"
    },
    {
        imagen1 : "/PRODUCTOS/ROPA/Ropa Niño/Ropa8/1.jpg",
        imagen2 : "/PRODUCTOS/ROPA/Ropa Niño/Ropa8/2.jpg",
        imagen3 : "/PRODUCTOS/ROPA/Ropa Niño/Ropa8/3.jpg",
        nombre: "Nombre Prenda:",
        talla: "Talla:",
        colores: "Colores Disponibles:",
        precio: "Precio: $$$$",
        codigo: "000053"
    },
    {
        imagen1 : "/PRODUCTOS/ROPA/Ropa Niño/Ropa9/1.jpg",
        imagen2 : "/PRODUCTOS/ROPA/Ropa Niño/Ropa9/2.jpg",
        imagen3 : "/PRODUCTOS/ROPA/Ropa Niño/Ropa9/3.jpg",
        nombre: "Nombre Prenda:",
        talla: "Talla:",
        colores: "Colores Disponibles:",
        precio: "Precio: $$$$",
        codigo: "000054"
    },
    {
        imagen1 : "/PRODUCTOS/ROPA/Ropa Niño/Ropa10/1.jpg",
        imagen2 : "/PRODUCTOS/ROPA/Ropa Niño/Ropa10/2.jpg",
        imagen3 : "/PRODUCTOS/ROPA/Ropa Niño/Ropa10/3.jpg",
        nombre: "Nombre Prenda:",
        talla: "Talla:",
        colores: "Colores Disponibles:",
        precio: "Precio: $$$$",
        codigo: "000055"
    },
    {
        imagen1 : "/PRODUCTOS/ROPA/Ropa Niño/Ropa11/1.jpg",
        imagen2 : "/PRODUCTOS/ROPA/Ropa Niño/Ropa11/2.jpg",
        imagen3 : "/PRODUCTOS/ROPA/Ropa Niño/Ropa11/3.jpg",
        nombre: "Nombre Prenda:",
        talla: "Talla:",
        colores: "Colores Disponibles:",
        precio: "Precio: $$$$",
        codigo: "000056"
    },
    {
        imagen1 : "/PRODUCTOS/ROPA/Ropa Niño/Ropa12/1.jpg",
        imagen2 : "/PRODUCTOS/ROPA/Ropa Niño/Ropa12/2.jpg",
        imagen3 : "/PRODUCTOS/ROPA/Ropa Niño/Ropa12/3.jpg",
        imagen4 : "/PRODUCTOS/ROPA/Ropa Niño/Ropa12/4.jpg",
        imagen5 : "/PRODUCTOS/ROPA/Ropa Niño/Ropa12/5.jpg",
        nombre: "Nombre Prenda:",
        talla: "Talla:",
        colores: "Colores Disponibles:",
        precio: "Precio: $$$$",
        codigo: "000057"
    },
    {
        imagen1 : "/PRODUCTOS/ROPA/Ropa Niño/Ropa13/1.jpg",
        imagen2 : "/PRODUCTOS/ROPA/Ropa Niño/Ropa13/2.jpg",
        imagen3 : "/PRODUCTOS/ROPA/Ropa Niño/Ropa13/3.jpg",
        imagen4 : "/PRODUCTOS/ROPA/Ropa Niño/Ropa13/4.jpg",
        imagen5 : "/PRODUCTOS/ROPA/Ropa Niño/Ropa13/5.jpg",
        imagen6 : "/PRODUCTOS/ROPA/Ropa Niño/Ropa13/6.jpg",
        imagen7 : "/PRODUCTOS/ROPA/Ropa Niño/Ropa13/7.jpg",
        imagen8 : "/PRODUCTOS/ROPA/Ropa Niño/Ropa13/8.jpg",
        imagen9 : "/PRODUCTOS/ROPA/Ropa Niño/Ropa13/9.jpg",
        imagen10 : "/PRODUCTOS/ROPA/Ropa Niño/Ropa13/10.jpg",
        nombre: "Nombre Prenda:",
        talla: "Talla:",
        colores: "Colores Disponibles:",
        precio: "Precio: $$$$",
        codigo: "000058"
    },
    {
        imagen1 : "/PRODUCTOS/ROPA/Ropa Niño/Ropa14/1.jpg",
        imagen2 : "/PRODUCTOS/ROPA/Ropa Niño/Ropa14/2.jpg",
        imagen3 : "/PRODUCTOS/ROPA/Ropa Niño/Ropa14/3.jpg",
        imagen4 : "/PRODUCTOS/ROPA/Ropa Niño/Ropa14/4.jpg",
        imagen5 : "/PRODUCTOS/ROPA/Ropa Niño/Ropa14/5.jpg",
        imagen6 : "/PRODUCTOS/ROPA/Ropa Niño/Ropa14/6.jpg",
        nombre: "Nombre Prenda:",
        talla: "Talla:",
        colores: "Colores Disponibles:",
        precio: "Precio: $$$$",
        codigo: "000059"
    },
    {
        imagen1 : "/PRODUCTOS/ROPA/Ropa Niño/Ropa15/1.jpg",
        imagen2 : "/PRODUCTOS/ROPA/Ropa Niño/Ropa15/2.jpg",
        imagen3 : "/PRODUCTOS/ROPA/Ropa Niño/Ropa15/3.jpg",
        imagen4 : "/PRODUCTOS/ROPA/Ropa Niño/Ropa15/4.jpg",
        imagen5 : "/PRODUCTOS/ROPA/Ropa Niño/Ropa15/5.jpg",
        imagen6 : "/PRODUCTOS/ROPA/Ropa Niño/Ropa15/6.jpg",
        imagen7 : "/PRODUCTOS/ROPA/Ropa Niño/Ropa15/7.jpg",
        imagen8 : "/PRODUCTOS/ROPA/Ropa Niño/Ropa15/8.jpg",
        imagen9 : "/PRODUCTOS/ROPA/Ropa Niño/Ropa15/9.jpg",
        imagen10 : "/PRODUCTOS/ROPA/Ropa Niño/Ropa15/10.jpg",
        nombre: "Nombre Prenda:",
        talla: "Talla:",
        colores: "Colores Disponibles:",
        precio: "Precio: $$$$",
        codigo: "000060"
    },
]